input: .
output: .retype
url: docs.copylink.to
branding:
  logo: assets/copylink-logo.png  
  title: CopyLink.to highlight.PRO
  label: Docs
links:
- text: Getting Started
  link: https://retype.com/guides/getting-started/
favicon: assets/favicon.ico
footer:
  copyright: "&copy; Copyright {{ year }}. All rights reserved."
name: GitHub Action for Retype
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: retypeapp/action-build@v2

      - uses: retypeapp/action-github-pages@v2
    with:
      branch: main
      update-branch: true